nodes:
    -
        host: "54.200.217.6"
        #host: "localhost"
        tcp_port: 12345
        udp_port: 12346
    -
        host: "54.201.11.70"
        #host: "localhost"
        tcp_port: 12345
        udp_port: 12346

logger:
    host: "erikhenriksson.se"
    tcp_port: 10000
