nodes:
    -
        host: "54.200.217.6"
        #host: "localhost"
        tcp_port: 12345
        udp_port: 12346
    -
        host: "54.201.11.70"
        #host: "localhost"
        tcp_port: 12345
        udp_port: 12346

logger:
    #host: "localhost"
    host: "54.201.40.23"
    tcp_port: 10000

workers:
    8
